### PR TITLE
Update to 1.1.0. Fixed all issues and made major change.

### PR DESCRIPTION
**Pull request by codepixar**

### CODE REVIEW

**Comment by cristianraiber** [comment]
@codepixar - why is this PR titled 1.1.0 when the last PR you did was v 1.2.2 ?

**Comment by codepixar** [comment]
Sorry for inconvenience. 1.2.2 was mistake so it is resolved last PR.

**Comment by cristianraiber** [comment]
@codepixar - you still need to revert Epsilon_ prefix in all classess/methods

**Comment by cristianraiber** [comment]
Far from being fixed:

https://github.com/ColorlibHQ/philosophy/pull/10/files#diff-58f480d3496f47e23f54f12f40996975R17
https://github.com/ColorlibHQ/philosophy/pull/10/files#diff-48d225cd93864f0943b839f4869bcd94R16

You should also remove Epsilon Framework & Epsilon Theme Dashboard from the actual theme files and reference them as git submodules. Take a look here: https://github.com/MachoThemes/portum/blob/master/.gitmodules

**Comment by cristianraiber** [comment]
@codepixar - Still waiting for the big fixes on this PR before it will be merged. See this: 
https://github.com/ColorlibHQ/philosophy/pull/10#issuecomment-424770875

**Comment by codepixar** [comment]
Hello cristianraiber,

We have already fixed all issues. Before PR we need to discuss about some issue.

1. You told Reduce theme ZIP size. We checked theme file when it is unzip it's size below 14 mb. After zip it's size become below 7 mb.

2. When theme zip download from git, Submodule files are not download in the theme. In the portum theme we found same issue when download from git.

We try to solve all issue. If possible you could let us know your advice or opinion.

You can check https://github.com/codepixar/philosophy/tree/dev

Thanks.

**Comment by cristianraiber** [comment]
@codepixar - please see this re. downloading as ZIP from GitHub: 
https://github.com/ColorlibHQ/Activello#repository-clonedownload-fire-fire-fire

re. 1. you could remove fonts completely from theme and load them from Google Fonts
re. 2. it's explained above

Waiting for your PR.

**Pull request closed without merging**
